# Generated by Django 4.1.5 on 2023-10-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0002_alter_categorymodel_options_alter_newsmodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='decriptions',
            new_name='descriptions',
        ),
    ]
